FROM python:3.11-slim

WORKDIR /app

# Install ultralytics and dependencies
RUN pip install --no-cache-dir ultralytics onnx

# Export script
COPY export-yolo-model.py .

CMD ["python", "export-yolo-model.py"]
